### ISSUE TITLE
Class Configurer Error : com.google.gson.JsonIOException

### ISSUE THREAD

**Issue by SSINGHPR** [grasshopper7/cuke7-extent-adapter-report#4]
Hello, 

com.google.gson.JsonIOException: Failed making field 'java.lang.Throwable#detailMessage' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.

I have JDK 17 and using your git project right as it is to run the sample tests and I am getting this error, I have not change anything in the project but when I download and run this. It only generates the Json and Spark report but Excel, HTML and PDF reports are not being generated. 

Is there anything wrong with my setup or what could be the issue ?

![image](https://github.com/grasshopper7/cuke7-extent-adapter-report/assets/108539752/79ab8855-6b01-4148-90bf-da22467d2147)

**Comment by grasshopper7** [comment]
This error is coming from the JSON formatter which is causing the report generation for excel pdf html to fail. Set the json to false and try extent.reporter.json.start=false. OR you can downgrade the jdk. I think extent core has been tested to max jdk 11.

Have a look at this - https://stackoverflow.com/questions/72769462/failed-making-field-property-accessible-either-change-its-visibility-or-write

Create an issue in extent report repository with the full stack trace.

com.google.gson.JsonIOException: Failed making field 'java.lang.Throwable#detailMessage' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.Gson.getAdapter(Gson.java:556)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.toJson(Gson.java:842)
	at com.google.gson.Gson.toJson(Gson.java:812)
	at com.google.gson.Gson.toJson(Gson.java:783)
	at com.aventstack.extentreports.reporter.JsonFormatter.flush(JsonFormatter.java:57)
	at com.aventstack.extentreports.reporter.JsonFormatter$1.onNext(JsonFormatter.java:37)
	at com.aventstack.extentreports.reporter.JsonFormatter$1.onNext(JsonFormatter.java:30)
	at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:310)
	at io.reactivex.rxjava3.subjects.PublishSubject.onNext(PublishSubject.java:226)
	at com.aventstack.extentreports.ReactiveSubject.onFlush(ReactiveSubject.java:83)
	at com.aventstack.extentreports.AbstractProcessor.onFlush(AbstractProcessor.java:95)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:279)
	at com.aventstack.extentreports.service.ExtentService.flush(ExtentService.java:47)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.finishReport(ExtentCucumberAdapter.java:301)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$8.receive(ExtentCucumberAdapter.java:137)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$8.receive(ExtentCucumberAdapter.java:134)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
	at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
	at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:111)
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:98)
	at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:250)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @42dafa95
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35)
	... 51 more

**Comment by SSINGHPR** [comment]
Thanks for your response, Do you think this is more of the Extent issue. I think they probably need to fix the new json format or whatever is throwing error in extent core. If so I can report the issue there and see if the extent dev will fix this. We strictly use jdk 17 so It's not a possibility for me to downgrade unfortunately. I am not sure if the line you shared will fix it because I am still getting the JSON and Klove reports but I am happy to give a try and see if this will fix it for me temporally at least.

**Comment by grasshopper7** [comment]
If you look at the stacktrace the error is coming from the JSONFormatter class which generates the json report. This solution has been tested by me. I do not have a Klov setup so will not be able to comment on it.

Extent core has just been updated to java 11 and i am not sure when it will be upgraded to 17.

I will move the creation of the json report to the end in the adaptor which should allow the creation of all reports. If it works will release a new versio.

**Comment by SSINGHPR** [comment]
Thanks so much for your prompt response, Looking forward for the your new version update to this framework as you mentioned so I can give it a try. I am not sure where I should put this line  extent.reporter.json.start=false so I will rather wait for the update and request you once you have it tested please push your changes so that I can try it again on my setup.

**Comment by grasshopper7** [comment]
My idea did not work. By putting it last the json report is not being generated. This will need to be fixed in the core code.

This line will be already there in the extent.properties file. It would currently be set to true. Change it to false.

This is the only solution I can currently provide. Thx.

**Comment by SSINGHPR** [comment]
Gotcha, I am trying it right now. I will also open a ticket for extent core and cross my fingers they might do something about it soon.

**Comment by SSINGHPR** [comment]
So I was finally able to get the html report generated after turning the json setting to false. Unfortunately I am hitting another exception that when I am using testng.xml to execute my tests I am getting this exception for pdf that pdf folder and file is being generated but it's 0kb size that means nothing is being written or converted with below error : 
![image](https://github.com/grasshopper7/cuke7-extent-adapter-report/assets/108539752/5a920af8-43e2-4ebd-9488-ba6313015cb2)

![image](https://github.com/grasshopper7/cuke7-extent-adapter-report/assets/108539752/70e6a81e-0e97-4068-85f4-8db41a935e85)
Can you please suggest something  for this issue ?

I also see the file pdf-config1.yaml present in the directory but I am not seeing it is mentioned or being used in the extent.properties ?

**Comment by grasshopper7** [comment]
Remove the '1' at the end of the config file. Add your testng.xml file. DO you have multiple runners in your project?

**Comment by SSINGHPR** [comment]
Yes I tried removing the 1 from pdf-config1.yaml and also by specifying the line “
extent.reporter.pdf.config=src/test/resources/pdf-config.yml” under extent.config but it didn’t solve the problem.

I am not sure what you mean by add your testng.xml file ? Yes I do have multiple runner files and also my project is using parallel execution. However every thing is getting executed via testng.xml

**Comment by grasshopper7** [comment]
Just rename the file without the 1 and it should work. Unless you want to change the default settings this config file does not matter. 

There is a parameter in the extent.properties - runner.count. Set it to the number of runners. This is experimental.
Multiple runners is an issue with pdf and excel files due to concurrent modification of single physical files. 

Can you attach the testng.xml here for my understanding.

If this fails then you can use the pdf maven plugin to generate the report? Refer to this - https://ghchirp.site/2224/.

**Comment by SSINGHPR** [comment]
Thanks once again for all your suggestions and help, Updating the file name and removing 1 did not help but only solution that worked updating the runner.count under extent.config.

So If I use your pdf maven plugin to generate the pdf report would I still have to update the runner.count in everytime ? I noticed if I add wrong number of runners it doesn't generate any reports at all and neither throws any error. only when the correct number of runners are provided then all the reports got generated without any error. I am just trying to avoid one more manual check every time before executing my tests. So if using your external maven plugin for pdf solve this problem where I don't need to update the runners I will be more than happy to utilize that instead.

Also I see a challenge due to that I think I would not be able to use Maven plugin since I had to disable genrating the JSON report as I was getting the error "Class Configurer Error : com.google.gson.JsonIOException" and It says json report need to be generated first ?
![image](https://github.com/grasshopper7/cuke7-extent-adapter-report/assets/108539752/1ea5cfe0-832b-4846-8032-fa8777af96c8)

**Comment by grasshopper7** [comment]
runner count setting is to fix the problem of concurrent modification of report in the case of pdf etc, when multiple runners are used. No need for this setting, if you do not use the cucumber adapter for generating pdf report.

The maven plugin for PDF report and the cucumber extent adapter are totally separate and there is no relationship between the two.

The maven plugin does not use the Extent JSON report but uses the Cucumber JSON report. They are two different things.

I am guessing you would use the cucumber adapter to generate the Spark and Html report. Make sure you turn off or remove the setting for generation of pdf excel and json report. The PDF report will be generated with the Maven plugin.
